## Tentaculo configuration file.
---
# System path where the game save's descriptors are store.
Game descriptors path: C:\Users\Javier\Documents\My Dropbox\Proyectos\Tentaculo\descriptors\
# System folder where the retrieved save files will be store. It will be created if doesn't exists.
Target path: C:\Users\Javier\Tentaculo\saves\